<?php
	$b_table="arcs,catalogs,config,dongtai,joinus,leaders,thumbs,videos";
	$tb[arcs]=1;
$tb[catalogs]=1;
$tb[config]=1;
$tb[dongtai]=1;
$tb[joinus]=1;
$tb[leaders]=1;
$tb[thumbs]=1;
$tb[videos]=1;

	$b_baktype=0;
	$b_filesize=300;
	$b_bakline=500;
	$b_autoauf=1;
	$b_dbname="chengjian";
	$b_stru=1;
	$b_strufour=0;
	$b_dbchar="auto";
	$b_beover=0;
	$b_insertf="replace";
	$b_autofield=",,";
	$b_bakdatatype=0;
	?>